name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Package extension
      run: npm run package
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v4
      with:
        name: pdf-docx-reader-${{ github.sha }}.vsix
        path: "*.vsix"
